### ISSUE TITLE
MRAN url has been changed

### ISSUE THREAD

**Issue by gogori** [andrie/miniCRAN#104]
Looks like Microsoft has changed the domain name of the cran mirror mran.microsoft.com to cran.microsoft.com. The default value does not work now.

**Comment by achubaty** [comment]
@gogori thanks for reporting. I've made changes to the `dev` branch address this issue. Please test if you can.

**Comment by andrie** [comment]
I flagged this to Microsoft, and they fixed the redirect. This means we don't have to take any action now.  Tests run locally, and should run successfully on CRAN during the next daily build.

@richcalaway
