### ISSUE TITLE
availPkgs is not a vector / documentation inaccuracy

### ISSUE THREAD

**Issue by dsteuer** [andrie/miniCRAN#108]
Hi! Documentation for pkgDep says:
 "availPkgs Vector of available packages.  Defaults to reading this list from CRAN, using
                available.packages()"

but you need the df returned from available.packages() with a column named "package" 
in line 
  pkgInAvail <- pkg %in% availPkgs[, "Package"]

Regards
Detlef

**Comment by andrie** [comment]
Thank you for catching and reporting!
