### ISSUE TITLE
mkRepo to local filepath throws unused argument error (repos = repos)

### ISSUE THREAD

**Issue by gturenchalk** [andrie/miniCRAN#109]
I was trying to execute a makeRepo command (linux using R 3.2.0) to create a local miniCRAN repository with a command similar to the following:
```
miniCRAN::makeRepo(NULL, path, type="source", repos=repo)
```
It threw the following error:
```
Error in utils::available.packages(contribUrl(repos, type = type, Rversion = Rversion),  :
  unused argument (repos = repos)
```
Looking at the code for pkDep.R in pkgAvail() :
https://github.com/andrie/miniCRAN/blob/b96cd01476ece3da0eb0badaf879eda1122c9af9/R/pkgDep.R#L131-L152

I see that the call to utils::available.packages() has a final argument of "repos = repos" which seems to be the source of the error.  By removing that argument (which seems to be superfluous for utils::available.packages()), I was able to install miniCRAN from local source and it allows my original makeRepo command to succeed.

**Comment by msteijaert** [comment]
I experienced the same issue for an older version of R (3.2.5) on which utils::available.packages() did not yet have the repos argument. For a more recent version, the same miniCRAN::makeRepo() call ran through without any errors. Is there a way to catch this, such that miniCRAN is also compatible with those older R versions?

**Comment by msteijaert** [comment]
I use the following as a workaround on older R versions (simply removing repos=repos as mentioned by gturenchalk) :

```
library(miniCRAN)
if(!"repos"%in%names(formals(utils::available.packages))) assignInNamespace("pkgAvail",
            function (repos = getOption("repos"), type = "source", Rversion = R.version,
                    quiet = FALSE)
            {
                if (!grepl("^http://|file:///", repos[1]) && file.exists(repos[1])) {
                    repos <- paste0("file:///", normalizePath(repos[1], mustWork = FALSE,
                                    winslash = "/"))
                }
                else {
                    if (!is.null(names(repos)) && isTRUE(unname(repos["CRAN"]) ==
                                    "@CRAN@")) {
                        repos <- MRAN()
                    }
                }
                ap <- function() {
                    utils::available.packages(miniCRAN:::contribUrl(repos, type = type,
                                    Rversion = Rversion), type = type, filters = list())
                }
                if (quiet)
                    suppressWarnings(ap())
                else ap()
            }, pos="package:miniCRAN")        
```

**Comment by andrie** [comment]
It's possible that the `backports` package might help here.

**Comment by andrie** [comment]
The `backports` package doesn't support `available.packages()`.

The argument was introduced in R-3.3.0 ([NEWS](https://cran.r-project.org/doc/manuals/r-release/NEWS.html)).
