### ISSUE TITLE
addLocalPackage doesn't permit mac.binary.el-capitan type

### ISSUE THREAD

**Issue by stumoodie** [andrie/miniCRAN#111]
When adding a Mac binary as a local package then it is only possible to specify the type as "mac.binary".   I am using MacOS High Sierra and the expected binary type is `mac.binary.el-capitan`.

While the call to addLocalPackage works:

```
miniCRAN::addLocalPackage(pkgs, path = repo_dir, pkgPath = pkg_source,
                          type = "mac.binary")
```

when you come to install the binary using install.packages it complains that the package cannot be found:

```
install.packages("ior", repos = c(local_repo_url, getOption("repos")))

Warning in install.packages :
  cannot open compressed file '/Users/stumoodie/foundation_git/interop/ior_installation/ior_repo/bin/macosx/el-capitan/contrib/3.4/PACKAGES', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
```

Moving the files located in `bin/macosx/contrib/3.4` to `bin/macosx/el-capitan/contrib/3.4` fixes the problem.

Could you allow addLocalPackage to accept a type of `mac.binary.el-capitan`?  Note that (I think) you can specify this type using addPackage().

**Comment by achubaty** [comment]
Did you try using `mac.binary.el-capitan` as the type?

```r
miniCRAN::addLocalPackage(pkgs, path = repo_dir, pkgPath = pkg_source,
                          type = "mac.binary.el-capitan")
```

**Comment by bleemayer** [comment]
The error is 
`Error in pkgFileExt(type) : Type mac.binary.el-capitannot recognised.` (continuing the thread).

**Comment by andrie** [comment]
I've pushed a potential fix to the `master` branch. Can you please install from github and let me know if this works?

**Comment by bleemayer** [comment]
Wow! It worked. Great job.

**Comment by andrie** [comment]
That's great to hear! Thanks for the feedback.
