### ISSUE TITLE
Imports in `pkgDep()`?

### ISSUE THREAD

**Issue by rkrug** [andrie/miniCRAN#118]
Hi

Is there a reason why I can't see the dependencies of imports? It is recommended to use `Imports` instead of `Depends` so it would make sense to scan the `Imports` as well?

**Comment by rkrug** [comment]
OK - thanks. Am I right, that only packages on CRAN can be visualised?

**Comment by andrie** [comment]
No.

http://andrie.github.io/miniCRAN/articles/miniCRAN-non-CRAN-repos.html
