### ISSUE TITLE
gzip: stdin: unexpected end of file /usr/bin/tar: Child returned status 128

### ISSUE THREAD

**Issue by sqlshep** [andrie/miniCRAN#120]
While trying to create a repo for tidyverse i get the error below for all 87 packages required from the makerepo

```r
gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘generics’ failed with message:
  cannot open the connection
tar (child): Cannot connect to c: resolve failed
```

```r
library(devtools)
install_github("andrie/miniCRAN")

revolution <- c(CRAN = "http://cran.us.r-project.org")
pkgs <- c("tidyverse")
pkgList <- pkgDep(pkgs, repos = revolution, type = "source", suggests = FALSE)

dir.create(pth <- file.path("c:/", "miniCRAN"))
makeRepo(pkgList, path = pth, repos = revolution)
```

**Comment by achubaty** [comment]
I am unable to reproduce Ubuntu 18.04.2 with R 3.5.3.

Can you confirm that all packages (`generics` in particular) downloaded correctly?

**Comment by sqlshep** [comment]
Yeah, just tested on my mac and it was fine too.  This is failing on an Azure Data Science Virtual Machine, so i may have some weird version problem with something. 

Generics did download, it does that on all 87 packages from tidyverse

**Comment by sqlshep** [comment]
Alright, this is a Microsoft Data Science Virtual Machine problem, not miniCran... leaving this out here in the unlikely event someone else stumbles onto it, but closing issue.
