### ISSUE TITLE
Updating the PACKAGES file sometimes gets stuck

### ISSUE THREAD

**Issue by Courvoisier13** [andrie/miniCRAN#127]
Hi,
I have noticed that sometimes the addPackage function gets stuck in the final stage after copying the package and does not update the PACKAGES, PACKAGES.gz and PACKAGES.rds files. I'm not sure what causes this. Here is an example. I am trying to add the `skimr` pacakge:

```
addPackage(pkgs = "skimr", path = pth, type = c("source"), Rversion = Rversion, deps = FALSE)
trying URL 'https://cran.rstudio.com/src/contrib/skimr_1.0.7.tar.gz'
Content type 'application/x-gzip' length 730379 bytes (713 KB)
downloaded 713 KB
```
Then it just hangs. the file skimr_1.0.7.tar.gz is in the folder miniCRAN3.4\src\contrib but the files 
PACKAGES, PACKAGES.gz and PACKAGES.rds  are not getting updated. If I interrupt the process, then install.packages from this repo will say package not found, even though the file is there and it can be installed directly if pointed directly to the file. 
I am suspecting this could be do to some antivirus blocking the copying and modifying of files quickly but I could be wrong. Any idea on how i can fix this?

**Comment by achubaty** [comment]
I cannot reproduce on an Ubuntu machine:

```r
> miniCRAN::makeRepo(pkgs = "BH", path = tmp)
trying URL 'https://cran.rstudio.com/src/contrib/BH_1.69.0-1.tar.gz'
Content type 'application/x-gzip' length 12378154 bytes (11.8 MB)
==================================================
downloaded 11.8 MB

[1] "/tmp/RtmpukhHX9/src/contrib/BH_1.69.0-1.tar.gz"

> addPackage(pkgs = "skimr", path = tmp, type = c("source"), deps = FALSE)
trying URL 'https://cran.rstudio.com/src/contrib/skimr_1.0.7.tar.gz'
Content type 'application/x-gzip' length 730379 bytes (713 KB)
==================================================
downloaded 713 KB

> list.files(file.path(tmp, "src", "contrib"))
[1] "BH_1.69.0-1.tar.gz" "PACKAGES"           "PACKAGES.gz"       
[4] "PACKAGES.rds"       "skimr_1.0.7.tar.gz"
```

```bash
$ cat /tmp/RtmpukhHX9/src/contrib/PACKAGES
Package: BH
Version: 1.69.0-1
License: BSL-1.0
MD5sum: d602666e5dae040489a1ed4f208f623b
NeedsCompilation: no

Package: skimr
Version: 1.0.7
Depends: R (>= 3.1.2)
Imports: cli, dplyr (>= 0.7), magrittr, pander, purrr, rlang, stats,
        stringr (>= 1.1), knitr (>= 1.2), tibble (>= 0.6), tidyr (>=
        0.7), tidyselect (>= 0.2.4)
Suggests: extrafont, rmarkdown, testthat (>= 2.0.0), withr, covr
License: GPL-3
MD5sum: 88302fd1e251195279fae74f38e36c2a
NeedsCompilation: no
```

so your antivirus suggestion may be the cause. need to confirm on a windows machine without [overly aggressive] AV. If that's the cause, I'm not sure how to deal with this (and test myself) -- perhaps an optional `delay` parameter could be added before the file copy step.

@andrie can you please try on windows?

**Comment by andrie** [comment]
How many packages do you have in your miniCRAN repo?

The very last step in `addPackages()` is to call `tools::write_PACKAGES()` to update the index files.  This process is very time consuming (about 2 seconds per package, IIRC).  So if you have a large number of packages this will take a long time.

This is one reason why you can specify the `writePACKAGES` argument.  If you set this to `FALSE` the index will not be updated. You can then later trigger a manual update using `updateRepoIndex()`.
