### ISSUE TITLE
Support multiple versions of a package

### ISSUE THREAD

**Issue by stefanoborini** [andrie/miniCRAN#131]
It's not clear if minicran supports multiple versions. For example, I installed ggplot 3.0.0 using addLocalPackage(). Then I installed ggplot 3.2.1, again with addLocalPackage(). 

I then used the minicran deployment with devtools::install_version(), and tried to install 3.0.0, but it's not found anymore. It does, however, install 3.2.1.

I tried to use "addOldPackage", but it just downloads an old version and puts it onto the minicran.

Is there a way for the minicran deployment to provide both versions?

**Comment by achubaty** [comment]
See #80 

> A true CRAN repository will not allow multiple versions of the same package. Whenever a new package version is added, the old version should move to the archive. This isn't implemented in `miniCRAN` yet.

**Comment by stefanoborini** [comment]
@achubaty so what's the idea when one has to certify tens of software components against their fixed dependencies?

**Comment by achubaty** [comment]
I'm not sure I understand what you're asking @stefanoborini. Until we/someone implement/s the archive, a workaround if you have multiple projects, each with a different subset of packages and versions, then you can maintain separate miniCRAN repos, or manually copy old versions to the archive for now. I know it's not ideal.

Note too, that the archive consists of source packages only.

Based on CRAN, the directory structure of the archive should look like `/src/contrib/Archive/pkgName/pkgName_x.y.z.tar.gz`. So each package gets a subdirectory for itself in `Archive`, and within a package subdir exists the source tarballs of previous versions.

I'd like to move any implementation discussion to the #122.

**Comment by stefanoborini** [comment]
Yes, let's move the discussion there.
