### ISSUE TITLE
Suggestion: Hide dependencies for some R packages in `plot.pkgDepGraph()`

### ISSUE THREAD

**Issue by phargarten2** [andrie/miniCRAN#132]
Thank you for creating package trees to try to map the dependencies, imports, and package links throughout CRAN. As packages become more intertwined, such maps become more vital for package developers to know the impact of other packages further down the list. However, such a graph can become unreadable due to sure volume of packages. 

Consider a package tree for gWQS package. 
```{r}
dg <- makeDepGraph("gWQS", suggests = FALSE, enhances = FALSE, includeBasePkgs = FALSE)
set.seed(1)  
plot(dg, legendPosition = c(-1, -1),      vertex.size = 10, cex = 0.7)
```
![image](https://user-images.githubusercontent.com/17706062/77355637-2a554f80-6d1b-11ea-927a-52dc93ec3162.png)

I know that **ggplot2** is a dependency for **miWQS**, but  **ggplot2** is dependent on a number of other packages. I would like just for **ggplot2** to be plotted perhaps in a different shape and its dependencies to be ignored in the graph so that I can read the tree created.  

If I really want to see the **ggplot2** dependencies, I can just create a separate graph:
```{r}
dg.ggplot2 <- makeDepGraph("ggplot2", suggests = FALSE, enhances = FALSE, includeBasePkgs = FALSE)
set.seed(422)
plot(dg.ggplot2, vertex.size = 0.10)
``` 
![image](https://user-images.githubusercontent.com/17706062/77355703-4d7fff00-6d1b-11ea-8fa0-8f633a614370.png)

I do realize that it is possible for a package dependent in **ggplot2** could also be used in **gWQS**. This is indeed the case here, as the **MASS** package is dependent in both **ggplot2** and **gWQS**. If possible, I prefer for it to remain on the "gWQS" graph; but if not, it can be hidden from sight and in the "ggplot2" bubble. This suggestion is not perfect, but it aims at trying to reduce the sure volume of packages in order for something to be plotted. 

Of course, I am using **ggplot2** as an example here, but having an argument in `plot.pkgDepGraph()`to hide dependencies of a dependent package will make the trees more readable to use. Other examples of many-dependent packages include the "tidyverse" packages as well.

Thank you.

**Comment by andrie** [comment]
Since `makeDepGraph()` produces an graph object, you can use `igraph` to manipulate this graph.

For example, you can use `distances()` to compute the distance matrix, then `induced_subgraph()` to extract only those nodes that are less than an arbitrary distance from your original node.

```r
library(igraph)
dg <- makeDepGraph("gWQS", suggests = FALSE, enhances = FALSE, includeBasePkgs = FALSE)

# compute distances
dist <- 
  dg %>% 
  distances(v = "gWQS")

# get subgraph with distance <= 1
sg <- induced_subgraph(dg, colnames(dist)[dist <= 1])

set.seed(1)  

# plot
sg %>% 
  plot(legendPosition = c(-1, -1), vertex.size = 10, cex = 0.7)
```

![image](https://user-images.githubusercontent.com/479998/77652869-d5a61480-6f66-11ea-83b5-f405a8a11ffa.png)

**Comment by phargarten2** [comment]
Thank you. I do appreciate your answer, and I can always go back to it if the graph goes overwhelming. However, I wonder if I can be more specific on which packages that I want to hide.  My goal is to see as many packages as possible in the plot while still be able to read it. In the example, I know that **ggplot2** has a lot of dependencies, so I want to hide all dependent packages from **ggplot2.** 
I know that the dg object has edges ... so if I can search the edges and remove "ggplot2 -->" that may get what I want.  I just don't know how to access the edges from a pkgDepGraph" or "igraph"   object.
```> dg
IGRAPH 88a7fd9 DN-- 104 266 -- 
+ attr: name (v/c), type (e/c)
+ edges from 88a7fd9 (vertex names):
 [1] truncnorm ->Rsolnp  digest    ->ggplot2 glue      ->ggplot2 gtable    ->ggplot2
 [5] isoband   ->ggplot2 MASS      ->ggplot2 mgcv      ->ggplot2 rlang     ->ggplot2
 [9] scales    ->ggplot2 tibble    ->ggplot2 withr     ->ggplot2 ellipsis  ->dplyr  
[13] assertthat->dplyr   glue      ->dplyr   magrittr  ->dplyr   pkgconfig ->dplyr  
[17] R6        ->dplyr   Rcpp      ->dplyr   rlang     ->dplyr   tibble    ->dplyr  
[21] tidyselect->dplyr   BH        ->dplyr   plogr     ->dplyr   Rcpp      ->dplyr  
[25] backports ->broom   dplyr     ->broom   generics  ->broom   nlme      ->broom  
[29] purrr     ->broom   reshape2  ->broom   stringr   ->broom   tibble    ->broom  
+ ... omitted several edges
 ```
Thanks
