### ISSUE TITLE
Installation on R <  4.0

### ISSUE THREAD

**Issue by sybrohee** [andrie/miniCRAN#134]
First of all, I would like to thank for all the work you put into
maintaining miniCRAN which is really useful in our daily use of R.

I tried to reinstall the miniCRAN library (in a docker image running ubuntu
18.04 and R3.6.1) but it appears that it cannot be installed anymore on
version of R < 4 as its dependency package XML is not available for R < 4.0
in his last version (3.99-0.4 since 2020-07-05).

You should maybe update the package stating that it is not working for R <
4.0 or editing the library DESCRIPTION file, mentioning the required version
of XML for miniCRAN to be installed properly. Actually, it seems to work
with version XML 3.99-0.3.

Kind regards,

Sylvain

**Comment by andrie** [comment]
Thank you for reporting this. I wasn't aware, and your prompt was helpful.

We're tracking this issue in #75 and I'm working it in #135

**Comment by andrie** [comment]
Fixed in #135
