### ISSUE TITLE
Vignette for using BioConductor needs update.

### ISSUE THREAD

**Issue by breidan** [andrie/miniCRAN#140]
I would like to create a miniCRAN repository from BioConductor. But the vignette explaining this is referring to `biocLite.R` which has not been in use since R3.5.

How would I go about this with `BiocManager`?

**Comment by padpadpadpad** [comment]
Have just stumbled across this problem too. Anyone got a fix?

**Comment by breidan** [comment]
I am not alone :-)
I have done some searching and found this:
[LocalBiocRepo.nb.html.zip](https://github.com/andrie/miniCRAN/files/6210278/LocalBiocRepo.nb.html.zip)
It is the HTML output of a Rmarkdown notebook. I adapted the paths to my needs and it works fine.

**Comment by dsjoho** [comment]
Thank you breidan! You saved me hours of work.
Based of that, this is the snippet I came up with on the download side with minicran.

```
# destrepodir is the base folder for the repository
r_version = "4.1"
bin_dir <-  paste0(destrepodir, "/bin/windows/contrib/", r_version)
bin_type <-  c("win.binary")
bioc_pkgs <- c("ConsensusClusterPlus")

bioc_avail = available.packages(contrib.url(BiocManager::repositories()))
bioc_deps = tools::package_dependencies(bioc_pkgs, bioc_avail, recursive=TRUE,)
download.packages(unique(c(bioc_pkgs, unlist(unname(bioc_deps)))), bin_dir,
                  repos=BiocManager::repositories(),
                  type=bin_type)

# And then update the PACKAGES file using minicran
updateRepoIndex(destrepodir, type = bin_type, Rversion = r_version)
```
