### ISSUE TITLE
addLocalPackage() gives error

### ISSUE THREAD

**Issue by spfeiffe** [andrie/miniCRAN#141]
I have the R package `rCharts.tar.gz` in my directory C:/Users/S.  

Then I do this...

```
setwd('C:/Users/S')

require(miniCRAN)

makeRepo(
pkgs=sort(pkgDep('tinytex')),
path='C:/Users/S/testRepo'
)

addLocalPackage(
pkgs='rCharts',
pkgPath='C:/Users/S',
path='C:/Users/S/testRepo'
)
```

... and get this error:

``` Error in FUN(X[[i]], ...) : subscript out of bounds ```

... Why?

(I am using miniCRAN-0.2.14 on R-4.0.3 (x64), running on Windows 10 Enterprise 10.0.17763)

**Comment by achubaty** [comment]
It fails, because the tarball filename does not include the version.

Typically, a build package will produce a tarball of the form `pkgName_1.2.3.tar.gz`.

How are you producing `rCharts.tar.gz`? You should be building it from source.

**Comment by spfeiffe** [comment]
Sorry, yes, that was the issue!  Thank you :)
