### ISSUE TITLE
miniCRAN::makeRepo downloads R-devel version of a package

### ISSUE THREAD

**Issue by contumax** [andrie/miniCRAN#153]
### miniCRAN::makeRepo downloads R-devel version of a package instead of the stable release

``` R
miniCRAN::makeRepo("MASS", path="", repos="https://cran.rstudio.com/", type="source")
```
Downloads the "7.3-60.1" version of the MASS package (for R4.4.0) instead of "7.3-60" (for current R4.3.2).

The issue is with the `miniCRAN:::pkgAvail` function that calls `available.packages`:
``` R
utils::available.packages(contribUrl(repos, type = type, 
                Rversion = Rversion), type = type, filters = list(), 
                repos = repos)
```
`filters` parameter should default to `NULL` not `list()`.

**Comment by andrie** [comment]
Thank you. I've fixed this in the main branch.
