### ISSUE TITLE
Get ready for CRAN release v0.3

### ISSUE THREAD

**Issue by andrie** [andrie/miniCRAN#154]
I'm hoping to release a new version to CRAN within the next few weeks.  I'm asking for community input whether there is anything urgent that we should still fix before such a release.

This is the current NEWS file:

* Support for `mac.binary.big-sur` (#152)
* Rewrite tests to use [Posit Public Package Manager](https://packagemanager.posit.co), since MRAN ceased to operate their service during 2023

Bug fixes:

* Don't download incorrect devel version of package (#153)

Internal:
* Rename internal function `MRAN()` to `p3m()` to reflect using Posit Public Package Manager (P3M)

Asking specific input from @achubaty , @vnijs , @ColinFay and @tonytonov because you've opened issues in the past.

**Comment by tonytonov** [comment]
Hi @andrie, no specific suggestions from me, thank you.

**Comment by andrie** [comment]
I've submitted v0.3.0 to CRAN.  🤞
