### ISSUE TITLE
Information is not displayed correctly in the README release status badge.

### ISSUE THREAD

**Issue by indenkun** [andrie/miniCRAN#158]
Dear Developers and Maintainers.

The CRAN release status badge in the README is not showing the correct information.

I think this is because the CRAN release status badge that README.md refers to is incorrect.

Looking at the logs, it seems that the wrong badge has been referred to since the following commit.
https://github.com/andrie/miniCRAN/commit/e124facd60fcc8861551f047f370874f0c56a227

Although `format: gfm` is specified, I confirmed that the badge information is displayed correctly when rendering with `devtools::build_readme(output_format = “github_document”)` and forcing github_document The following is a sample of the results.
https://github.com/indenkun/miniCRAN/tree/readme-test

I can also pull requests for the ones above if needed.

**Comment by andrie** [comment]
Thanks for reporting this.

I have now attempted various fixes, but none of these fixes the display of the badge.

The URL for the badge itself  (https://www.r-pkg.org/badges/version/miniCRAN) resolves correctly when I open this in a browser, but not from the README.

It also makes no difference when I change the yaml to:

```
---
output: github_document
---
```

It's a mystery.

**Comment by andrie** [comment]
Although the problem persists locally, once I push to github everything now renders correctly.
