### ISSUE TITLE
What is the desired behaviour for addOldPackage() when it creates duplicates?

### ISSUE THREAD

**Issue by andrie** [andrie/miniCRAN#47]
Right now, this function creates a duplicate and throws a warning

This may leave the repository in an inconsistent state.

Should we remove the duplicate?

**Comment by sebastian-c** [comment]
One of the reasons I'm not using `miniCRAN` is because it doesn't allow archiving of packages as CRAN does. Could archiving be a solution to the duplicate problem?

**Comment by achubaty** [comment]
@sebastian-c I agree that archiving (see also #80) may help here. Not sure how soon I'll be able to build this.

**Comment by andrie** [comment]
I agree that archiving is a better solution.
