### ISSUE TITLE
`addOldPackage` redundancy with `devtools::install_version`?

### ISSUE THREAD

**Issue by achubaty** [andrie/miniCRAN#55]
I just discovered `devtools::install_version`, which may be useful inside `addOldPackage`.

I haven't looked at it in detail, but is it worth using this code or sticking with what we have?

**Comment by andrie** [comment]
I'll take a look

**Comment by andrie** [comment]
I think we need a general improvement in handling old packages in an archive, and then the end user can use `devtools::install_version()` to install a specific version of a package.
