### ISSUE TITLE
Is it possible to create a new repository from the repository file PACKAGES?

### ISSUE THREAD

**Issue by josehur** [andrie/miniCRAN#79]
What I want is to create a new repository using the information contained in the PACKAGES file from other repository?? Is this currently possible using miniCRAN functions?

Thanks

**Comment by andrie** [comment]
There isn't a convenience function to do this directly, so you'll have to extract the package names from the PACKAGES file.

This should be a fairly simple regular expression.

Try something like this:

```r
pkgs <- "Package: A3
Version: 1.0.0
Depends: R (>= 2.15.0), xtable, pbapply
Suggests: randomForest, e1071
License: GPL (>= 2)

Package: ABC.RAP
Version: 0.9.0
Depends: R (>= 3.1.0)
Imports: graphics, stats, utils
Suggests: knitr, rmarkdown
License: GPL-3

Package: ABCanalysis
Version: 1.1.2
Depends: R (>= 2.10)
Imports: plotrix
License: GPL-3
"

pkgs <- strsplit(pkgs, "\n")[[1]]

regex <- "^Package: (.*)$"
idx <- grep(regex, pkgs)
pkgs[idx]
gsub(regex, "\\1", pkgs[idx])
```
