### ISSUE TITLE
Multiple versions of packages in miniCRAN

### ISSUE THREAD

**Issue by statquant** [andrie/miniCRAN#80]
There is something I do not understand, it looks like addOldPackage show a warning when there are 2 versions of the same package. This is precisely what I want, I want to be able to install the lattest package version from my miniCran when another developer install an old version.
Is this supported ?
If not is there another package that does ?
Or maybe that does not make sense and I'll be happy to learn

**Comment by sfweller** [comment]
The miniCRAN package itself does not really have a automated way to maintain different versions of specific R packages. You can do that, but you need to take care of the versions of the packages yourself, if they reside in the same repository. 

For more information, you can refer to the information on this page:
https://mran.microsoft.com/web/packages/miniCRAN/vignettes/miniCRAN-introduction.html

in the section that discusses 'Adding a older version of a package from CRAN'.

You can also use the 'checkpoint' package instead, which is also available from CRAN. That package allows you to install packages created at different snapshot dates, so you can keep different versions of a package in a different local snapshot repository.

Hope this helps.

Steve Weller

**Comment by statquant** [comment]
Hello Steve, thanks for your answer. I have been reading the vignettes and that's the reason of my question. They clearly mention that duplicates packages have to be 'cleared'. Are you saying that it is fine to leave them be and that the repo will be fine ?

Let me discribe my use case: I want to centralize the r packages used by several people (so they stop installing personal libraries everywhere), but I want to allow them to get the latest version as soon as it is out. So I need to be able to create a repo that have several versions.
The idea is that when people create their packages, they would use packrat to isolate what they need, and to install the package they would use only the miniCRAN.
Right now I miss a miniCRAN like that would allow me to deal with several versions and to which I can add packages as I like fron cran/github/...
Regards

**Comment by shapenaji** [comment]
Hi miniCRAN! I had a pressing need for the version control internally at my company, so I wrote up my own package (`cranium`) and put it up on github doing something a bit similar, but specifically for versioning. When multiple versions exist in my repo, I store each one under a new name in the index. So `install.packages('miniCRAN_0.1.0', 'http://path/to/my/repo')` will install version 0.1.0, while `install.packages('miniCRAN', 'http://path/to/my/repo')` will install the most recent version in the repository. https://github.com/shapenaji/cranium/

**Comment by statquant** [comment]
Nice !
Will try that!

**Comment by andrie** [comment]
A true CRAN repository will not allow multiple versions of the same package. Whenever a new package version is added, the old version should move to the archive.  This isn't implemented in `miniCRAN` yet.
