### ISSUE TITLE
Getting 'Error in basename(prev)' when calling addPackage

### ISSUE THREAD

**Issue by mungojam** [andrie/miniCRAN#99]
When calling:

```
addPackage(pkgs = binaryPackage, path = localCran, repos = remoteCran, 
    type = "win.binary", Rversion = version, writePACKAGES = FALSE)
```

It happens with type="source" too I think.

I think it happens when I ask it to add a package that I have already added. I've worked around it for now. I can try and reproduce it more later if it isn't clear from the stack trace below what the issue is

> Error in basename(prev) : a character vector argument expected 
> 8. basename(prev) 
> 7. grep(paste0("^", x), basename(prev)) 
> 6. FUN(X[[i]], ...) 
> 5. lapply(dupes, function(x) {
>    grep(paste0("^", x), basename(prev))
> }) 
> 4. FUN(X[[i]], ...) 
> 3. lapply(type, function(t) {
>   prev <- checkVersions(pkgs = pkgs, path = path, type = t, 
>        Rversion = Rversion)
>    prev.df <- getPkgVersFromFile(prev) ... 
> 2. addPackage(pkgs = binaryPackage, path = localCran, repos = remoteCran, 
    type = "win.binary", Rversion = version, writePACKAGES = FALSE)

**Comment by andrie** [comment]
What is the value of `binaryPackage` ?

**Comment by andrie** [comment]
Can you please make the example reproducible?

**Comment by mungojam** [comment]
Sure, I've managed to reproduce now and it only seems to affect forecast package:

This fails:
```
addPackage(pkgs = "forecast", path = "C:\\Users\\Me\\Mran\\snapshot\\2017-09-27", repos = "https://mran.microsoft.com/snapshot/2017-09-27",
           type = "source", Rversion = 3.4)
```

This works:
```
addPackage(pkgs = "Rcpp", path = "C:\\Users\\Me\\Mran\\snapshot\\2017-09-27", repos = "https://mran.microsoft.com/snapshot/2017-09-27",
+            type = "source", Rversion = 3.4)
```

**Comment by mungojam** [comment]
One thing to add, I am completely clearing out the contrib folder before each attempt.

It manages to install plenty of packages before it fails. I tried with writePACKAGES = FALSE and it still fails. It works with deps=FALSE, so it must be a particular package it is failing on

> ...
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/testthat_1.0.2.tar.gz'
> Content type 'application/octet-stream' length 147298 bytes (143 KB)
> downloaded 143 KB
> 
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/expsmooth_2.3.tar.gz'
> Content type 'application/octet-stream' length 245921 bytes (240 KB)
> downloaded 240 KB
> 
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/rticles_0.4.1.tar.gz'
> Content type 'application/octet-stream' length 686206 bytes (670 KB)
> downloaded 670 KB
> 
> Error in basename(prev) : a character vector argument expected

I've then tried it with rticles, and it fails 

```
addPackage(pkgs = "rticles", path = "C:\\Users\\Me\\Mran\\snapshot\\2017-09-27", repos = "https://mran.microsoft.com/snapshot/2017-09-27",
           type = "source", Rversion = 3.4)
```

> ...
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/praise_1.0.0.tar.gz'
> Content type 'application/octet-stream' length 6100 bytes
> downloaded 6100 bytes
> 
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/R6_2.2.2.tar.gz'
> Content type 'application/octet-stream' length 322959 bytes (315 KB)
> downloaded 315 KB
> 
> trying URL 'https://mran.microsoft.com/snapshot/2017-09-27/src/contrib/testthat_1.0.2.tar.gz'
> Content type 'application/octet-stream' length 147298 bytes (143 KB)
> downloaded 143 KB
> 
> **Error in basename(prev) : a character vector argument expected**

I tried "testthat" which is the last in this list and it worked fine. All a bit odd.

I debugged in a bit and got:

> Browse[2]> .Internal(basename(path))
> Error: a character vector argument expected
> Browse[2]> path
> $source
> character(0)

Need to leave this for a bit. Hope you're able to reproduce it.

**Comment by dirkschumacher** [comment]
I get the same error message. Here is a reproducible example:

```R
cran_path <- "cran"
dir.create(cran_path)
repo <- "https://cran.r-project.org"
miniCRAN::makeRepo(pkgs = c(), path = cran_path, type = "win.binary", repos = repo)
packages <- "forecast"
miniCRAN::addPackage(packages, Rversion = "3.4",
                     path = cran_path, type = "win.binary", repos = repo)
```

I suspect that the call to `checkVersions` leads to the problem. Maybe because `sapply` is not type stable? https://github.com/RevolutionAnalytics/miniCRAN/blob/f7fac463c11a07aa776c1af8cfd45f6175abc2bb/R/addPackages.R#L29

Also, changing the package from `aprof` to e.g. `forecast` would make the tests fail:
https://github.com/RevolutionAnalytics/miniCRAN/blob/1b1d7a8a2fee8a83385e2827bd3f0a39d9238161/tests/testthat/test-5-updateRepo.R#L42

**Comment by sfweller** [comment]
Hi, Dirk.  I can't reproduce the problem with the latest version of Microsoft R Open(3.4.2). Your 'forecast' example works fine, even if I already have the package pre-installed.

**Comment by dirkschumacher** [comment]
I reproduced it with CRAN R 3.4 on Windows and my mac. Maybe there is a different cause then 🤔

**Comment by mungojam** [comment]
Happens for me with CRAN R 3.4.2 (and previously R 3.4.1). I think it didn't happen the other day when I tried the same thing, just to make it more confusing!

**Comment by andrie** [comment]
I am creating a new branch `99-addPackage-fail` to experiment and trace the issue

**Comment by andrie** [comment]
This issue is reproducible in Windows.  

The error occurs in `addPackage()`, when the logic to find duplicates finds a dupe in `curr.df` and attempts to delete the file from `prev.df` but the file doesn't exist in `prev.df`.

I'm not sure why this can ever be true, though???

**Comment by andrie** [comment]
I think I've traced the error.  Now testing.

The root cause is that `checkVersions()` returns a matrix, but some of the downstream functions assumes the result is a character vector.

I'm hacking together a workaround (just use first column).  This will be good enough for `addPackages()` and should fix the immediate problem.

It needs some refactoring in the longer term, though.

**Comment by andrie** [comment]
In this case `sapply()` is not the culprit, but thanks for the hint.

It is related though, since in a different place `sapply()` simplified to a matrix, where a matrix doesn't make any sense, and it's better to keep as a list, i.e. use `simplify = FALSE`.

**Comment by andrie** [comment]
```
==> devtools::test()

Loading miniCRAN
Loading required package: testthat
Testing miniCRAN
<U+2714> | OK F W S | Context
<U+2714> |  4       | pkgAvail [2.6 s]
<U+2714> | 13       | pkgDep [2.5 s]
<U+2714> | 21       | makeDepGraph  [20.8 s]
<U+2714> |  0       | makeRepo [0.6 s]
<U+2714> |  5       |  - source [3.8 s]
<U+2714> |  5       |  - win.binary [4.1 s]
<U+2714> |  5       |  - mac.binary [3.7 s]
<U+2714> |  5       |  - mac.binary.mavericks [3.7 s]
<U+2714> | 10       | makeRepo from local miniCRAN [4.4 s]
<U+2714> |  4       | updateRepo [7.8 s]
<U+2714> |  3       |  - Add packages to repo (win.binary) [71.9 s]
<U+2714> |  3       |  - Add packages to repo (mac.binary) [54.7 s]
<U+2714> |  3       |  - Add packages to repo (source) [67.8 s]
<U+2714> |  7       |  - Add local packages to repo (win.binary) [2.5 s]
<U+2714> |  7       |  - Add local packages to repo (mac.binary) [6.4 s]
<U+2714> |  7       |  - Add local packages to repo (source) [14.9 s]
<U+2714> |  8       |  - Check for updates (win.binary) [23.6 s]
<U+2714> |  8       |  - Check for updates (mac.binary) [14.6 s]
<U+2714> |  8       |  - Check for updates (source) [26.6 s]
<U+2714> |  4       | Check for duplicate files [16.6 s]
<U+2714> |  2       | get CRAN description [4.0 s]
<U+2714> |  5       | pkgDep [1.5 s]

= Results =========================================================================================================
OK:       137
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by wangyuchen** [comment]
Hi, I ran into this error when using `addLocalPackage`.

https://github.com/andrie/miniCRAN/blob/b96cd01476ece3da0eb0badaf879eda1122c9af9/R/addPackages.R#L289

When I debugged into it, `prev` is a list, where its first element is a character vector called `source`. I think the `as.character()` call is supposed to be on `prev$source`? This generates an error and prevented me from adding a local package.

**Comment by achubaty** [comment]
I'm unable to replicate. `as.character(prev)` works fine without needing to do `as.character(prev[[1]])`.

Are you using most recent version? can please you provide your `sessionInfo()` and a reproducible example?

**Comment by chase-meadows** [comment]
Hey I had this issue yesterday while trying to use the addLocalPackage function. I took a deep dive into your package, and it was consistently failing out when declaring "same <- which(basename(as.character(prev)) %in% files"

I believe the issue had something to do with the structure of the list 'prev' argument. I changed it to "    same <- which(basename(as.character(prev$source)) %in% files)" and this corrected the issue for me. Hope this helps other people with a similar issue! 

`addLocalPackage <- function(pkgs = NULL, pkgPath = NULL, path = NULL,
                            type = "source", Rversion = R.version,
                            writePACKAGES = TRUE, deps = FALSE,
                            quiet = FALSE, build = FALSE) {
  
  
  if (is.null(path) || is.null(pkgs) || is.null(pkgPath)) {
    stop("path, pkgs, and pkgPath must be specified.")
  }
  
  stopifnot(dir.exists(file.path(pkgPath)))
  
  # build local package if needed
  if (isTRUE(build)) {
    warning("Building local packages is still being tested.")
    if (requireNamespace("devtools", quietly = TRUE)) {
      lapply(pkgs, function(x) {
        devtools::build(pkg = file.path(pkgPath, x), path = pkgPath,
                        binary = ifelse(type == "source", FALSE, TRUE),
                        quiet = quiet)
      })
    } else {
      stop("To build packages, you must first install the 'devtools' package.")
    }
  }

  # get list of pre-built packages for each type, filter by pkgs to be added
  sapply(type, function(t) {
    repoPath <- file.path(path, repoPrefix(t, Rversion))
    if (!dir.exists(repoPath)) dir.create(repoPath, recursive = TRUE)
    files <- .listFiles(pkgs = pkgs, path = pkgPath, type = t)
    # check for previous package version and omit if identical
    prev <- checkVersions(pkgs, path)
    same <- which(basename(as.character(prev$source)) %in% files)
    
    if (length(same)) {
      files <- files[-same]
      if (length(files) == 0) {
        if (!quiet) message("All packages up to date. Nothing to add.")
        return(invisible(NULL))
      }
    }
    
    # copy other packages to their respective folders
    lapply(files, function(x) {
      f.src <- file.path(pkgPath, x)
      f.dst <- file.path(repoPath, x)
      
      file.exists(f.src)
      
      if (!isTRUE(quiet)) message("copying ", x, "\n")
      file.copy(from = f.src, to = f.dst)
    })
    
    # check to ensure they all copied successfully
    copied <- file.exists(file.path(repoPath, files))
    if (!all(copied)) {
      warning("the following ", t, " packages were not copied:\n",
              paste(files[!copied], sep = ", "))
    }
    
    # remove previous package versions
    if (length(prev[-same]) > 0) unlink(prev[-same])
  })
  
  # write package index for each folder:
  index <- updateRepoIndex(path = path, type = type, Rversion = Rversion)
  
  invisible(index)
}`

**Comment by andrie** [comment]
I'm also unable to replicate, and have added unit tests in `tests/testthat/test-8-test-8-addLocalPackage.R`.

Note that these tests are only in the `dev` branch right now.  If anybody could edit my test case so I can reproduce, I would appreciate it.
